datasets: # name of the dataset builder
  # Be careful not to append minus sign (-) before split to avoid itemizing
  dataset_name: diorgpg
  annotations:
    train: /data1/users/yangcong/data/GPG/annotations/dior-gpg/dior-gpg-train.json
    val: /data1/users/yangcong/data/GPG/annotations/dior-gpg/dior-gpg-val.json
    # test: /data1/users/yangcong/data/GPG/annotations/dior-gpg/dior-gpg-test.json
  images: /data1/users/yangcong/data/GPG/images
