datasets: # name of the dataset builder
  # Be careful not to append minus sign (-) before split to avoid itemizing
  dataset_name: diorvg
  annotations: /data1/users/yangcong/data/GPG/annotations/dior-vg.json
  images: /data1/users/yangcong/data/GPG/images
